server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db:3306/test_management_db?createDatabaseIfNotExist=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

rabbitmq:
  queue:
    name: test_run_jobs_queue
  exchange:
    name: test_run_exchange
  routing:
    key: test_run_jobs_key

  dlq:
    name: test_run_jobs_dlq
  dlx:
    name: test_run_dlx
  dlq-routing:
    key: test_run_dlq_key
